<?php

namespace Devinci\LoginCore\Migrations;

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Class CreateUserTable
 * @package Devinci\LaravelEssential\Migrations
 *
 * This migration file is auto-generated by devinci/laravel-essentials
 */

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->dropColumn('name'); // Remove the 'name' column

            // Check if 'first_name' column exists, if not, add it
            if (!Schema::hasColumn('users', 'first_name')) {
                $table->string('first_name');
            }

            // Check if 'last_name' column exists, if not, add it
            if (!Schema::hasColumn('users', 'last_name')) {
                $table->string('last_name');
            }

            // Check if 'email' column exists, if not, add it
            if (!Schema::hasColumn('users', 'email')) {
                $table->string('email')->unique();
            }

            // Check if 'username' column exists, if not, add it
            if (!Schema::hasColumn('users', 'username')) {
                $table->string('username')->unique();
            }

            // Check if 'password' column exists, if not, add it
            if (!Schema::hasColumn('users', 'password')) {
                $table->string('password');
            }

            // Check if 'account_status' column exists, if not, add it
            if (!Schema::hasColumn('users', 'account_status')) {
                $table->string('account_status');
            }


        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->string('name')->nullable();
        });
    }


    /**
     * Publish the migration file to Laravel base path for Migrations.
     *
     * @return void
     */
    public static function publish()
    {
        $stubPath = (__DIR__.'/../../stubs/create_user.stub');
        $destinationPath = database_path('migrations/' . date('Y_m_d_His') . '_modify_user_table.php');

        copy($stubPath, $destinationPath);
    }
};
